name: C++ CI (Presets)

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [dev-debug-asan, ci-tests-release]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update
        sudo apt-get install -y ninja-build g++-14

    - name: Configure CMake
      env:
        CXX: g++-14
      run: cmake --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }}

    - name: Debug CMake Cache
      run: grep "ENABLE_TESTING" build/ci-tests-release/CMakeCache.txt

    - name: Test
      run: ctest --preset ${{ matrix.preset }}