name: C++ CI (Fedora)

on: [push, pull_request]

jobs:
  build-and-test:
    # Оставляем ubuntu-latest как хост, но запускаем всё в контейнере
    runs-on: ubuntu-latest
    container:
      image: fedora:41 # Или fedora:rawhide для самого свежего железа

    steps:
    - name: Install dependencies
      run: |
        dnf install -y \
          gcc-c++ \
          cmake \
          ninja-build \
          git \
          libstdc++-devel

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake --preset ${{ matrix.preset }}
      strategy:
        matrix:
          preset: [dev-debug-asan, ci-tests-release]

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }}

    - name: Test
      run: ctest --preset ${{ matrix.preset }}